version: "3.8"

name: Open-Music-API-V2
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:16.3-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: ../.env
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: openmusic

volumes:
  postgres-data:
