version: "3.8"

name: OPEN-MUSIC-API-V3
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - my-network

  postgres:
    image: postgres:16.3-bookworm
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-network

  redis:
    image: redis:7.2.5-bookworm
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
